### ISSUE TITLE
Práctica 6 Modelo de Negocios en Bizagi Web 3.0

### ISSUE THREAD

**Issue by JoseABCruz** [SistemasTecTlaxiaco/actividad-6-practica-de-proceso-de-negocio-con-web-30-equipo-hjfs#1]

**Comment by SANDRAVELASCO** [comment]
[Práctica 6 para realizar el diseño de proceso de negocio (Fiestas).pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-proceso-de-negocio-con-web-30-equipo-hjfs/files/9620395/Practica.6.para.realizar.el.diseno.de.proceso.de.negocio.Fiestas.pdf)

**Comment by FedericoVictorianoSierra** [comment]
[Práctica 6 Modelo de Negocios en Bizagi Web 3.0 (Federico Victoriano Sierra).pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-proceso-de-negocio-con-web-30-equipo-hjfs/files/9620732/Practica.6.Modelo.de.Negocios.en.Bizagi.Web.3.0.Federico.Victoriano.Sierra.pdf)

**Comment by Heidi-19** [comment]
[Práctica 6-Heidi Lucy Bautista Sanjuan 5USC.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-proceso-de-negocio-con-web-30-equipo-hjfs/files/9620735/Practica.6-Heidi.Lucy.Bautista.Sanjuan.5USC.pdf)

**Comment by JoseABCruz** [comment]
[Práctica 6  Modelo de Negocios en Bizagi Web 3.0 (José Antonio Balbuena Cruz).pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-proceso-de-negocio-con-web-30-equipo-hjfs/files/9620753/Practica.6.Modelo.de.Negocios.en.Bizagi.Web.3.0.Jose.Antonio.Balbuena.Cruz.pdf)

**Comment by Elisahadad** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
